// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyClyELoyZtoH0DTd27rn3Tp-UMGLz6rB9s',
    appId: '1:39196458212:web:618573baa5e0d2c0e740f1',
    messagingSenderId: '39196458212',
    projectId: 'fir-test-3a617',
    authDomain: 'fir-test-3a617.firebaseapp.com',
    storageBucket: 'fir-test-3a617.firebasestorage.app',
    measurementId: 'G-6Y204YSHJ3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCDxCzX4EDxCIZCrWXnxUYMxW49P8CmxbE',
    appId: '1:39196458212:android:b26da8c65343929ee740f1',
    messagingSenderId: '39196458212',
    projectId: 'fir-test-3a617',
    storageBucket: 'fir-test-3a617.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB6qpPTYeerq1jti1XIUS0q2noB4gpAszE',
    appId: '1:39196458212:ios:c16e8e2be0d0af7de740f1',
    messagingSenderId: '39196458212',
    projectId: 'fir-test-3a617',
    storageBucket: 'fir-test-3a617.firebasestorage.app',
    iosBundleId: 'com.example.authFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB6qpPTYeerq1jti1XIUS0q2noB4gpAszE',
    appId: '1:39196458212:ios:c16e8e2be0d0af7de740f1',
    messagingSenderId: '39196458212',
    projectId: 'fir-test-3a617',
    storageBucket: 'fir-test-3a617.firebasestorage.app',
    iosBundleId: 'com.example.authFirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyClyELoyZtoH0DTd27rn3Tp-UMGLz6rB9s',
    appId: '1:39196458212:web:33f72947ba7598aee740f1',
    messagingSenderId: '39196458212',
    projectId: 'fir-test-3a617',
    authDomain: 'fir-test-3a617.firebaseapp.com',
    storageBucket: 'fir-test-3a617.firebasestorage.app',
    measurementId: 'G-YYCGJLRTG9',
  );

}